## 高速配列計算のためのNumPy多次元配列
Pythonエコシステムの中心がNumPy。高速数値計算のためのデータ構造、つまり多次元配列を提供。このレシピでは、多次元配列の基本概念を紹介。

In [2]:
import random # 乱数モジュール
import numpy as np # NumPy

In [26]:
%precision 3 
# 数値出力を小数第3位までの表示とする

'%.3f'

### まずは通常の計算

In [27]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [9]:
x[:3], y[:3]

([0.794, 0.995, 0.646], [0.251, 0.271, 0.505])

In [11]:
# 要素ごとの和を求める
z = [x[i] + y[i] for i in range(n)]
z[:3]

[1.045, 1.267, 1.152]

In [15]:
# 実行時間の計算
%timeit [x[i] + y[i] for i in range(n)]

1 loop, best of 3: 266 ms per loop


In [17]:
# 同じ操作をNumPyで
xa = np.array(x) # リストを配列に変換
ya = np.array(y)

### NumPyによる計算

In [19]:
xa[:3]

array([ 0.794,  0.995,  0.646])

In [21]:
za = xa + ya
za[:3]

array([ 1.045,  1.267,  1.152])

In [24]:
%timeit za + ya

100 loops, best of 3: 4.27 ms per loop


NumPyを使った計算は上の例の約50倍の速さで終了。

### 実験2

In [29]:
%timeit sum(x) # pure Python
%timeit np.sum(xa) # NumPy

100 loops, best of 3: 12.1 ms per loop
1000 loops, best of 3: 1.15 ms per loop


### 実験3

In [31]:
d = [abs(x[i] -y[j]) for i in range(1000) for j in range(1000)]

In [33]:
d[:3]

[0.532, 0.062, 0.013]

In [35]:
da = np.abs(xa[:1000,None] -ya[:1000])

In [37]:
da

array([[ 0.542,  0.522,  0.288, ...,  0.426,  0.724,  0.53 ],
       [ 0.744,  0.724,  0.49 , ...,  0.627,  0.925,  0.732],
       [ 0.395,  0.375,  0.141, ...,  0.278,  0.576,  0.382],
       ..., 
       [ 0.338,  0.318,  0.084, ...,  0.221,  0.519,  0.325],
       [ 0.074,  0.095,  0.329, ...,  0.191,  0.107,  0.087],
       [ 0.22 ,  0.2  ,  0.035, ...,  0.103,  0.401,  0.207]])

In [38]:
%timeit [abs(x[i] -y[j]) for i in range(1000) for j in range(1000)]
%timeit np.abs(xa[:1000,None] - ya[:1000])

1 loop, best of 3: 410 ms per loop
100 loops, best of 3: 6.52 ms per loop
